### ISSUE TITLE
Not compatible with black terminal background

### ISSUE THREAD

**Issue by hubert3** [NitinJami/keychaineditor#12]
keychaineditor assumes that the terminal background colour is white - It looks like this with a black background, you're left with an invisible cursor:

<img width="636" alt="screen shot 2016-03-29 at 1 15 26 pm" src="https://cloud.githubusercontent.com/assets/947995/14095919/7591636c-f5b0-11e5-86a2-da92edc041a7.png">

The current text output colour should be reset before keychaineditor exits so you don't have to manually reset.

**Comment by NitinJami** [comment]
Oops, sorry for that. I no longer apply colors. Thanks
