### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by 0x4d4e** [NitinJami/keychaineditor#5]
keychaineditor crashes on iOS 9.0.2 with a segfault:

```
# ./keychaineditor --action dump
Segmentation fault: 11
```

Furthermore, the error code -25308 (errSecInteractionNotAllowed) - running keychaineditor on a locked device - is not handled by the application (don't know if this error was also thrown on locked devices with iOS 8):

```
Unhandled Error: Please contact developer to report this error. Error code: -25308
```

**Comment by apokharel** [comment]
fixed here: https://github.com/apokharel/keychaineditor

**Comment by NitinJami** [comment]
The issues are now fixed. Commit 36f32e7. Please download the latest binary!
