### ISSUE TITLE
setObjectForKey: object cannot be nil

### ISSUE THREAD

**Issue by l3gi0nQQ** [NitinJami/keychaineditor#6]
in function: NSString\* determineTypeAndReturnNSString(id accountValue)
the result of "[[NSString alloc] initWithData:accountValue encoding:NSUTF8StringEncoding]" can be nil.
this will cause a crash in function : "void prepareJsonOutput(NSDictionary *results, NSString *find)"

so, i made a little change as below:
//========================================================================
NSString\* determineTypeAndReturnNSString(id accountValue) {

```
// If NSData, convert it to NSString and return...
if ([accountValue isKindOfClass:[NSData class]]) {
    NSString *result = [[NSString alloc] initWithData:accountValue encoding:NSUTF8StringEncoding];
    if (!result) {
        return [[NSString alloc] init];
    }
    return result;
}

return accountValue;
```

}
//========================================================================

this worked for me.

**Comment by NitinJami** [comment]
This is now fixed. Thanks!
